'use client'

import { useEffect, useState } from 'react'

type Commission = {
  id: string
  title: string
  description: string | null
  price: number | null
  currency: string | null
  status: string
  deadline: string | null
  created_at: string
}

type Profile = {
  display_name: string | null
  username: string
  email?: string
}

type Props = {
  commission: Commission
  artist: Profile
}

export default function InvoiceButton({ commission, artist }: Props) {
  const [ready, setReady] = useState(false)

  useEffect(() => {
    setReady(true)
  }, [])

  async function handleExport() {
    const { jsPDF } = await import('jspdf')
    const doc = new jsPDF()

    const currency = commission.currency ?? 'USD'
    const price = commission.price ?? 0
    const artistName = artist.display_name || artist.username
    const invoiceNo = commission.id.slice(0, 8).toUpperCase()
    const createdDate = new Date(commission.created_at).toLocaleDateString('en-GB', {
      day: 'numeric', month: 'long', year: 'numeric'
    })
    const deadlineDate = commission.deadline
      ? new Date(commission.deadline).toLocaleDateString('en-GB', {
          day: 'numeric', month: 'long', year: 'numeric'
        })
      : 'No deadline'

    const pageW = doc.internal.pageSize.getWidth()

    // Header bar
    doc.setFillColor(127, 119, 221)
    doc.rect(0, 0, pageW, 40, 'F')

    // ARIN logo text
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(24)
    doc.setFont('helvetica', 'bold')
    doc.text('ARIN', 20, 26)

    // INVOICE text
    doc.setFontSize(11)
    doc.setFont('helvetica', 'normal')
    doc.text('COMMISSION INVOICE', pageW - 20, 20, { align: 'right' })
    doc.setFontSize(10)
    doc.text(`#${invoiceNo}`, pageW - 20, 30, { align: 'right' })

    // Reset color
    doc.setTextColor(30, 30, 30)

    // Artist info
    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.text('From', 20, 58)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.text(artistName, 20, 66)
    doc.text(`@${artist.username}`, 20, 73)

    // Invoice info (right)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.text('Invoice Details', pageW - 20, 58, { align: 'right' })
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.text(`Date: ${createdDate}`, pageW - 20, 66, { align: 'right' })
    doc.text(`Deadline: ${deadlineDate}`, pageW - 20, 73, { align: 'right' })

    // Divider
    doc.setDrawColor(220, 220, 220)
    doc.line(20, 82, pageW - 20, 82)

    // Commission title section
    doc.setFillColor(248, 247, 255)
    doc.rect(20, 90, pageW - 40, 30, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12)
    doc.setTextColor(83, 74, 183)
    doc.text(commission.title, 28, 103)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(120, 120, 120)

    const statusMap: Record<string, string> = {
      open:        'Pending',
      in_progress: 'In Progress',
      completed:   'Completed',
      cancelled:   'Cancelled',
    }
    doc.text(`Status: ${statusMap[commission.status] ?? commission.status}`, 28, 113)

    // Description
    if (commission.description) {
      doc.setTextColor(30, 30, 30)
      doc.setFontSize(10)
      doc.setFont('helvetica', 'bold')
      doc.text('Description', 20, 135)
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(9)
      doc.setTextColor(80, 80, 80)

      const lines = doc.splitTextToSize(commission.description, pageW - 40)
      doc.text(lines, 20, 143)
    }

    // Price table
    const tableY = commission.description ? 170 : 140

    doc.setDrawColor(220, 220, 220)
    doc.setFillColor(245, 244, 254)
    doc.rect(20, tableY, pageW - 40, 10, 'F')

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(83, 74, 183)
    doc.text('Description', 25, tableY + 7)
    doc.text('Amount', pageW - 25, tableY + 7, { align: 'right' })

    doc.setTextColor(30, 30, 30)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.text(commission.title, 25, tableY + 18)
    doc.text(`${currency} ${price.toFixed(2)}`, pageW - 25, tableY + 18, { align: 'right' })

    doc.setDrawColor(220, 220, 220)
    doc.line(20, tableY + 24, pageW - 20, tableY + 24)

    // Total
    doc.setFillColor(127, 119, 221)
    doc.rect(20, tableY + 26, pageW - 40, 14, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.text('Total', 25, tableY + 36)
    doc.text(`${currency} ${price.toFixed(2)}`, pageW - 25, tableY + 36, { align: 'right' })

    // Footer
    doc.setTextColor(160, 160, 160)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.text('Generated by ARIN · arin.art', pageW / 2, 280, { align: 'center' })
    doc.text(`Invoice #${invoiceNo}`, pageW / 2, 286, { align: 'center' })

    doc.save(`ARIN-Invoice-${invoiceNo}.pdf`)
  }

  if (!ready) return null

  return (
    <button
      onClick={handleExport}
      className="w-full border border-purple-200 text-purple-600 rounded-lg py-2.5 text-sm hover:bg-purple-50 transition-colors font-medium"
    >
      📄 Export Invoice PDF
    </button>
  )
}